# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
# Specify multiple "source" and "destination" pairs if you want to copy
#   from multiple sources or to multiple destinations.
# If you are not copying any files to the Amazon EC2 instance, then remove the
#   "files" section altogether. A blank or incomplete "files" section
#   may cause associated deployments to fail.
files:
  - source: build/
    destination: /home/ec2-user/website/build/
  - source: node_modules/
    destination: /home/ec2-user/website/node_modules/
  - source: package.json
    destination: /home/ec2-user/website/
hooks:
  # For each deployment lifecycle event, specify multiple "location" entries
  #   if you want to run multiple scripts during that event.
  # You can specify "timeout" as the number of seconds to wait until failing the deployment
  #   if the specified scripts do not run within the specified time limit for the
  #   specified event. For example, 900 seconds is 15 minutes. If not specified,
  #   the default is 1800 seconds (30 minutes).
  #   Note that the maximum amount of time that all scripts must finish executing
  #   for each individual deployment lifecycle event is 3600 seconds (1 hour).
  #   Otherwise, the deployment will stop and CodeDeploy will consider the deployment
  #   to have failed to the Amazon EC2 instance. Make sure that the total number of seconds
  #   that are specified in "timeout" for all scripts in each individual deployment
  #   lifecycle event does not exceed a combined 3600 seconds (1 hour).
  # For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
  #   you can specify "runas" in an event to
  #   run as the specified user. For more information, see the documentation.
  # If you do not want to run any commands during a particular deployment
  #   lifecycle event, remove that event declaration altogether. Blank or
  #   incomplete event declarations may cause associated deployments to fail.
  ApplicationStop:
    - location: scripts/aws/codedeploy/ApplicationStop.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/aws/codedeploy/BeforeInstall.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/aws/codedeploy/ApplicationStart.sh
      timeout: 300
