name: Deploy to CodeDeploy

on:
  push:
    branches: 'main'

jobs:
  deploy:
    environment: codedeploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create CodeDeploy Deployment
        env:
          AWS_CODEDEPLOY_APP_NAME: ${{ secrets.AWS_CODEDEPLOY_APP_NAME }}
          AWS_CODEDEPLOY_GROUP_NAME: ${{ secrets.AWS_CODEDEPLOY_GROUP_NAME }}
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.AWS_CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ env.AWS_CODEDEPLOY_GROUP_NAME }} \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
